parserOptions:
  ecmaFeatures:
    jsx: true
env:
  browser: true
extends:
  - eslint-config-getkey
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - "plugin:@typescript-eslint/recommended"
plugins:
  - react
parser: '@typescript-eslint/parser'
settings:
  react:
    version: detect
rules:
  react/prop-types:
    - off
  '@typescript-eslint/interface-name-prefix':
    - off
  '@typescript-eslint/no-unused-vars':
    - error
    - ignoreRestSiblings: true
  '@typescript-eslint/ban-ts-comment':
    - off
  no-shadow: # must use the TS-specific rule instead
    - off
  '@typescript-eslint/no-shadow':
    - error
